### ISSUE TITLE
`DOCTRINE_DBAL_210` incorrectly renames some `Doctrine\DBAL\Types\Type` usages

### ISSUE THREAD

**Issue by Blacksmoke16** [rectorphp/rector-doctrine#100]
For example, if using [custom types](https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#custom-mapping-types):

```php
<?php

\Doctrine\DBAL\Types\Type::addType('money', 'My\Project\Types\MoneyType');
```

would be updated to:

```php
<?php

\Doctrine\DBAL\Types\Types::addType('money', 'My\Project\Types\MoneyType');
```

Which is invalid since these methods only exist on the `Doctrine\DBAL\Types\Type` version.

Introduced in https://github.com/rectorphp/rector/pull/2514.

**Comment by samsonasik** [comment]
fixed at https://github.com/rectorphp/rector-doctrine/pull/104
