### ISSUE TITLE
Add DoctrinePHPDocInfoRector to fix Entity PHPDoc by Doctrine Metadata

### ISSUE THREAD

**Issue by alexander-schranz** [rectorphp/rector-doctrine#141]
Similar to https://github.com/rectorphp/rector-phpunit/pull/114, https://github.com/rectorphp/rector-phpunit/pull/114 / https://github.com/rectorphp/rector-phpunit/pull/115

I would like to set the PHPDocInfo `@var` based on doctrine metadata. Via [phpstan-doctrine](https://github.com/phpstan/phpstan-doctrine) phpstan already knows the correct type from the Doctrine Metadata () which should be set to the property and getter of that property.

I'm not yet sure how I can access the expected PHPStan type. Any hints how to achieve this would be welcome.

**Comment by johanadivare** [comment]
Its been a while since this issue was created. I would suggest to start a pull request containing test with what you want to achieve. That way other devs can easly see what it is you want and what might then be usefull. At least that is what i would do

**Comment by TomasVotruba** [comment]
Agreed with @johanadivare , better kick of with PR, as it's more clear what is your goal. It usually takes 5-10 days to finish up such rules. So go for it :muscle: 



Closing as accepted to avoid keep issue tracker focus on unclear issues that needs our attention.
