### ISSUE TITLE
Add rule to update string events with constants

### ISSUE THREAD

**Issue by stefantalen** [rectorphp/rector-doctrine#146]
Lets add a rule to replace event strings with the corresponding class constants (Just like the `Criteria` constants)
```diff
<?php

declare(strict_types=1);

namespace App\Subscriber\Doctrine;

use Doctrine\Common\EventSubscriber;
use Doctrine\ORM\Event\LifecycleEventArgs;
use Doctrine\ORM\Event\PreUpdateEventArgs;
+use Doctrine\ORM\Events;

class DoctrineSubscriber implements EventSubscriber
{

    public function getSubscribedEvents(): array
    {
        return [   
-            'prePersist',
-            'preUpdate',
+            Events::prePersist,
+            Events::preUpdate,
        ];
    }

    public function prePersist(LifecycleEventArgs $args) {
        //...
    }
    public function preUpdate(PreUpdateEventArgs $eventArgs) {
        //...
    }
}
```
I'll see if I can implement this in the future

**Comment by TomasVotruba** [comment]
This might help:
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#replacestringwithclassconstantrector

**Comment by stefantalen** [comment]
@TomasVotruba I tried using the [StringToClassConstantRector](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#stringtoclassconstantrector), which works but I think the rule is too general. Is there some way to scope it to certain interfaces only?

**Comment by TomasVotruba** [comment]
@stefantalen That would require a standalone rule based on this one, as the context of global vs interface-based is a different one.

**Comment by TomasVotruba** [comment]
Closing for lack of feedback, to keep issue tracker focus on unclear issues that needs our attention.

**Feel free to send PR with the rule when you find time :+1:**

Thank you for understanding :slightly_smiling_face:
