### ISSUE TITLE
New rule for iterate() => toIterable() since 2.8.x

### ISSUE THREAD

**Issue by johanadivare** [rectorphp/rector-doctrine#157]
With https://github.com/doctrine/orm/pull/7885 & https://github.com/doctrine/orm/pull/8293  there was a new function introduced to loop. 

Add a rule the will move all `iterate()` to `toIterable()`. And make sure we fix cases like:
```diff
-$results = $em->select('e')->from('entity')->getQuery()->iterate();
+$results = $em->select('e')->from('entity')->getQuery()->toIterable();
foreach($resuls as $result) {
-   $entityIsHere = $result[0];
+   $entityIsHere = $result;
}
```

Also create a `doctrine-orm-28.php`

**Comment by TomasVotruba** [comment]
Hi @johanadivare ,

this seems like easy pick, could you send PR for it?

**Comment by johanadivare** [comment]
I think to replace the function is pretty straight forward but then seeing where the output is used and to change accordingly is more difficult, i could work on a draft and see how far i come
