### ISSUE TITLE
[Rule Idea] Add a rule which remove automatically unneeded postgresql schema migrations

### ISSUE THREAD

**Issue by alexander-schranz** [rectorphp/rector-doctrine#162]
There is an issue in doctrine migration which add some unexpected schema migrations in the down migration: https://github.com/doctrine/dbal/issues/1110:

In my project it did contain the follwing:

<img width="920" alt="Bildschirmfoto 2023-04-21 um 16 07 37" src="https://user-images.githubusercontent.com/1698337/233657183-01decbac-0275-47b0-8b5c-4fbabfc824e6.png">

```php
        $this->addSql('CREATE SCHEMA metric_helpers');
        $this->addSql('CREATE SCHEMA user_management');
        $this->addSql('CREATE SCHEMA public');
```

Think rector could be used to make sure this addSql never exists.

**Comment by TomasVotruba** [comment]
This sounds like a valid idea! **Feel free to send PR with such a rule :+1:**

Closing as accepted to avoid keep issue tracker focus on unclear issues that needs our attention.
