### ISSUE TITLE
NullabilityColumnPropertyTypeResolver default false instead of true?

### ISSUE THREAD

**Issue by jirinapravnik** [rectorphp/rector-doctrine#190]
I ma not sure if I understand it correctly. 

But in this function, there should be default false, not true?
https://github.com/rectorphp/rector-doctrine/blob/8afdccb30c1ab88b2d159470fa9ac8d56dee6362/src/NodeManipulator/NullabilityColumnPropertyTypeResolver.php#L50

By default ORM\Column is nullable=false. If I don't have nullable neiehter in the attribute nor in phpdoc, it souhldn't be nullable for property. Am I missing something?

Example here also show ignoring nullable:false in the attribute, but it can be due to others refactoring rules.
![image](https://github.com/rectorphp/rector-doctrine/assets/2507653/3d135225-58da-4039-87b0-f4ef8e89de21)

**Comment by TomasVotruba** [comment]
Hi, it could be the case, as nullable=false is removing null and makes English double-negative hard :)

Could you send a PR with your proposal so we see how it changes tests fixtures?

**Comment by TomasVotruba** [comment]
Closing per https://github.com/rectorphp/rector-doctrine/pull/191#issuecomment-1868981410
