### ISSUE TITLE
New rule for "Passing an array for the first argument to QueryBuilder::select() is deprecated"

### ISSUE THREAD

**Issue by rpkamp** [rectorphp/rector-doctrine#218]
We're getting the following deprecation warnings from Doctrine DBAL:

```
Passing an array for the first argument to QueryBuilder::select() is deprecated, pass each value as an individual variadic argument instead.
```

So for example
```php
$queryBuilder->select(['field1', 'field2', 'field3', 'etc']);
```

should become

```php
$queryBuilder->select('field1', 'field2', 'field3', 'etc');
```

**Comment by TomasVotruba** [comment]
@samsonasik Hi Abdul, could you cover this with new rule or close it?

**Comment by samsonasik** [comment]
@TomasVotruba I will try, 

@rpkamp what doctrine specific version that start deprecating it?

**Comment by TomasVotruba** [comment]
@samsonasik I think the first version is 2.11 - https://github.com/doctrine/dbal/pull/3853, https://github.com/doctrine/dbal/issues/3837

**Comment by samsonasik** [comment]
Ok 👍

**Comment by samsonasik** [comment]
I created PR 

- https://github.com/rectorphp/rector-doctrine/pull/244

for it .

**Comment by rpkamp** [comment]
Thanks @samsonasik !
