### ISSUE TITLE
support for @Assert

### ISSUE THREAD

**Issue by lcp0578** [rectorphp/rector-doctrine#225]
@Assert\Regex
@Assert\NotBlank

**Comment by stefantalen** [comment]
Hi @lcp0578, 

Thanks for your message, can you elaborate on the issue here? What's up with the annotations 🙂?

**Comment by TomasVotruba** [comment]
@lcp0578  This is already supported in Symfony Rector set: https://github.com/rectorphp/rector-symfony/blob/main/config/sets/symfony/symfony52-validator-attributes.php


@stefantalen Thanks for ping, I missed this :)
