### ISSUE TITLE
New Rector to read entity property type from the Attribute

### ISSUE THREAD

**Issue by kaznovac** [rectorphp/rector-doctrine#237]
The [TypedPropertyFromColumnTypeRector](https://github.com/rectorphp/rector-doctrine/blob/main/rules/CodeQuality/Rector/Property/TypedPropertyFromColumnTypeRector.php) exists, but as it seams it works only on Annotations not on Attributes.

**Comment by TomasVotruba** [comment]
That would be great addition. Could you send a PR?

**Comment by TomasVotruba** [comment]
Closing as accepted to avoid keep issue tracker focus on unclear issues that needs our attention.

Feel free to send PR with it :+1:
