### ISSUE TITLE
Incorrect behavior of TypedPropertyFromColumnTypeRector

### ISSUE THREAD

**Issue by stefantalen** [rectorphp/rector-doctrine#255]
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/720d70fc-be2c-4a49-a67d-6c35f25f2d76

```php
<?php

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
final class DemoEntity
{
    /**
     * @ORM\Column(type="decimal", scale=1, precision=4, nullable=false)
     */
    protected $productDiscount = 0;
}
```

### Responsible rules

* `TypedPropertyFromColumnTypeRector`

## Expected Behavior

```diff
/**
 * @ORM\Column(type="decimal", scale=1, precision=4, nullable=false)
 */
- protected $productDiscount = 0;
+ protected float $productDiscount = 0;
```

**Comment by samsonasik** [comment]
That seems expected per map:

https://github.com/rectorphp/rector-doctrine/blob/b419ce77041e75b65020e88b7b3ddab40f56d169/src/NodeManipulator/ColumnPropertyTypeResolver.php#L59

see 

https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/basic-mapping.html#doctrine-mapping

If there is a specific type changed on specific doctrine orm above 2.6, the specific rule need to be created for that.

**Comment by stefantalen** [comment]
Thanks for the link to the Doctrine documentation!

Looks like the project I'm working on made some own assumptions.

In this case the default property value assignment is incorrect, it should not be `0`.
