### ISSUE TITLE
Classes constants `Doctrine\ORM\Query\Lexer::T_*` deprecated in favor of `Doctrine\ORM\Query\TokenType::T_*`

### ISSUE THREAD

**Issue by julienfastre** [rectorphp/rector-doctrine#294]
According to [the upgrade guide](https://github.com/doctrine/orm/blob/2.19.x/UPGRADE.md#deprecate-doctrineormquerylexert_-constants), class constants `Doctrine\ORM\Query\Lexer::T_*` are now deprecated, in favor of `Doctrine\ORM\Query\TokenType::T_*`.

Can we write a rector rule for this ?

**Comment by samsonasik** [comment]
configured rule can be used for that imo, and register to specific rule set, for example, using `RenameClassConstFetchRector`, ref https://getrector.com/demo/32a9f4b8-817d-4e28-b792-ce751f953c2d

**Comment by samsonasik** [comment]
@julienfastre could you create a PR on it under https://github.com/rectorphp/rector-doctrine/blob/main/config/sets/doctrine-orm-29.php with `RenameClassConstFetchRector` configurable, eg https://getrector.com/demo/32a9f4b8-817d-4e28-b792-ce751f953c2d ?

Thank you.

**Comment by julienfastre** [comment]
yes, I'm working on it.
