### ISSUE TITLE
TypedPropertyFromToOneRelationTypeRector should taken into account parent definition

### ISSUE THREAD

**Issue by oleg-andreyev** [rectorphp/rector-doctrine#305]
Demo https://getrector.com/demo/7b7afb36-937e-4e66-8561-c9a0ea2cc01a

![image](https://github.com/rectorphp/rector-doctrine/assets/1244112/a0dfaa28-dc07-4199-9bfd-26c59539926a)
![image](https://github.com/rectorphp/rector-doctrine/assets/1244112/ac7e90bc-31f4-4ab6-aae7-8faa78edb360)

**Comment by TomasVotruba** [comment]
Thank you for your report and demo link!

We'll need a failing test case in a pull-request, so we have it covered in Rector.
You can click "Create a Test" button at demo page.
