### ISSUE TITLE
[DOCTRINE_COLLECTION_22] constant to enum error for querybuilder

### ISSUE THREAD

**Issue by johanadivare** [rectorphp/rector-doctrine#325]
When i use `DOCTRINE_COLLECTION_22` it will replace my `Doctrine\\Common\\Collections\\Criteria::DESC` to Doctrine\\Common\\Collections\\Order::DESC` but this causes the following error: `TypeError: Doctrine\ORM\QueryBuilder::orderBy(): Argument #2 ($order) must be of type ?string, Doctrine\Common\Collections\Order given, called in /srv/Repository/BlogRepository.php on line 103`

The replacement should actually be `Doctrine\\Common\\Collections\\Order::DESC->value` @julienfastre asked if this would maybe cause problems see:  https://github.com/rectorphp/rector-doctrine/pull/297#issuecomment-1983489234

I think we should replace with the `->value` call?

**Comment by TomasVotruba** [comment]
Thanks for reporting! Fix you suggest would be great 👍

**Comment by julienfastre** [comment]
Not sure its a good idea: as I remember, in issue https://github.com/rectorphp/rector-doctrine/issues/315, it was discussed that, maybe: 

- we should not replace the "ASC" and "DESC" strings by constants in annotations, 
- but we should keep the replacement where those string (or the previous constants) are in use as argument in `Criteria::orderBy`

**Comment by TomasVotruba** [comment]
@julienfastre Would it fix this bug? 🙏

**Comment by julienfastre** [comment]
I'll try to find some time next week or the week after, @TomasVotruba .

**Comment by julienfastre** [comment]
Regarding [to this comment](https://github.com/doctrine/orm/issues/11313#issuecomment-2214570323), do you think that we should remove all usage of `Criteria::ASC` and `Criteria::DESC` outside of a `Criteria::orderBy` by the `'ASC'` and `'DESC'` string ?
