### ISSUE TITLE
[DOCUMENTATION] The main README.md shows an outdated way of converting attribute

### ISSUE THREAD

**Issue by alexis-boyer** [rectorphp/rector-doctrine#327]
On the README.md file it shows, in order to convert Doctrine annotation into PHP attribute, a command as follow 
```
use Rector\Config\RectorConfig;
use Rector\Doctrine\Set\DoctrineSetList;

return RectorConfig::configure()
    ->withSets([
        DoctrineSetList::DOCTRINE_CODE_QUALITY,
    ]);
```

This is however the old way to do and is not supported anymore. The official documentation shows another way (https://getrector.com/documentation/set-lists)
```
use Rector\Config\RectorConfig;

return RectorConfig::configure()
    ->withAttributesSets(doctrine: true);
```

**Comment by TomasVotruba** [comment]
Thanks for reporting! Could you send PR to fix it? :+1:

**Comment by alexis-boyer** [comment]
I do it as soon as I can.

**Comment by samsonasik** [comment]
Resolved at https://github.com/rectorphp/rector-doctrine/pull/328
