### ISSUE TITLE
NotImplementedYetException when using private ?int $varName = null;

### ISSUE THREAD

**Issue by weeger** [rectorphp/rector-doctrine#34]
Hi,

I love rector and rector doctrine <3. But.

```php
<?php

namespace App\Wex\BaseBundle\Entity\Traits;

use Doctrine\ORM\Mapping as ORM;

trait LinkedToAnyEntity
{
    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private ?int $entityId = null;
}
```

```bash
vendor/bin/rector process -vvv src/Wex/BaseBundle/Entity/Traits/LinkedToAnyEntity.php
```

Result : 

```bash
[applying] Rector\Doctrine\Rector\Property\CorrectDefaultTypesOnEntityPropertyRector

In CorrectDefaultTypesOnEntityPropertyRector.php line 116:
                                                      
  [Rector\Core\Exception\NotImplementedYetException]  
```                                                      

Probably the same problem as https://github.com/rectorphp/rector/issues/5454
And should be solved by https://github.com/rectorphp/rector/pull/5974

Same issue with 

\Rector\Doctrine\Rector\Property\CorrectDefaultTypesOnEntityPropertyRector::class
\Rector\Doctrine\Rector\Property\RemoveRedundantDefaultPropertyAnnotationValuesRector::class

Thanks

**Comment by samsonasik** [comment]
please provide failing test case or reproducible repository for it. To create failing test case, you can do:

1. open https://getrector.org/demo
2. add failing test case
3. the output still not as expected? click "Create a Test" button.

**Comment by TomasVotruba** [comment]
Resolved in https://github.com/rectorphp/rector-doctrine/pull/52
