### ISSUE TITLE
Doctrine Annotations silently dropped during Attributes migration due to syntax error

### ISSUE THREAD

**Issue by caugner** [rectorphp/rector-doctrine#348]
I used the following script to convert Doctrine annotations to attributes:

```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Doctrine\Set\DoctrineSetList;

return function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/src/',
    ]);
    $rectorConfig->sets([
        DoctrineSetList::ANNOTATIONS_TO_ATTRIBUTES,
    ]);
};
```

Unfortunately, some annotations were silently dropped, due to annotations with improperly closed parenthesis (in this case an extra closing parenthesis before the `@ORM\Entity` annotation, which doesn't prevent Doctrine from parsing the annotations properly):

```patch
 /**
- * @ORM\Table(name="changelog",
- *   indexes={
- *     @ORM\Index(name="entity", columns={"entity_class", "entity_id"}),
- *   }
- * ))
- * @ORM\Entity(repositoryClass="ChangeLogRepository")
- * @ORM\HasLifecycleCallbacks
  */
+#[ORM\Table(name: 'changelog')]
+#[ORM\Index(name: 'entity', columns: ['entity_class', 'entity_id'])]
 class ChangeLog
 {
   // ...
 }
```

I'm not sure if Rector could better handle this case, but I wanted to report this issue just in case.

PS: The project uses Psalm and PHPCS, but both didn't catch the annotation syntax error.

**Comment by TomasVotruba** [comment]
Thank you for your report!

We'll need an isolated failing demo link from: http://getrector.com/demo,
that way we can reproduce the bug.
