### ISSUE TITLE
PHP 8.4 Implicitly marking parameter as nullable is deprecated, the explicit nullable type must be used instead

### ISSUE THREAD

**Issue by PhilETaylor** [rectorphp/rector-doctrine#352]
PHP Deprecated:  Rector\Doctrine\NodeManipulator\ColumnPropertyTypeResolver::__construct(): Implicitly marking parameter $doctrineTypeToScalarType as nullable is deprecated, the explicit nullable type must be used instead in /Users/phil/Sites/example.com/vendor/rector/rector/vendor/rector/rector-doctrine/src/NodeManipulator/ColumnPropertyTypeResolver.php on line 51

Deprecated: Rector\Doctrine\NodeManipulator\ColumnPropertyTypeResolver::__construct(): Implicitly marking parameter $doctrineTypeToScalarType as nullable is deprecated, the explicit nullable type must be used instead in /Users/phil/Sites/example.com/vendor/rector/rector/vendor/rector/rector-doctrine/src/NodeManipulator/ColumnPropertyTypeResolver.php on line 51

**Comment by PhilETaylor** [comment]
Hmm I think this has already been addressed as the current lin 51 in the main branch, is not the same as the line 51 that I have on my mac :)

**Comment by samsonasik** [comment]
That seems after downgrade, nullable should be added when add null default value. This should be covered on downgrade process to support php 8.4 syntax while downgrade to php 7.4

**Comment by samsonasik** [comment]
Reproduced at https://getrector.com/demo/876d65e2-7925-4f73-bf92-a208de6dc5ff

**Comment by samsonasik** [comment]
https://github.com/rectorphp/rector-downgrade-php/pull/243

**Comment by samsonasik** [comment]
Re-open, needs to relook more :)

**Comment by samsonasik** [comment]
I created new fix for it:

- https://github.com/rectorphp/rector-downgrade-php/pull/245
