### ISSUE TITLE
MakeEntityDateTimePropertyDateTimeInterfaceRector is flawed

### ISSUE THREAD

**Issue by stof** [rectorphp/rector-doctrine#356]
DBAL has 2 different set of types for datetime-based types:

- the `*_immutable` types work with `DateTimeImmutable`
- the `*_mutable` types (constant names have the `_mutable` suffix while values don't) work with `DateTime`

Changing the `DateTime` property types in entities to `DateTimeInterface` is not consistent with this behavior. While DBAL 3.x and older support writing a `DateTimeInterface` value in such property, it triggers a deprecation warning. And DBAL 4.x throws an exception, forbidding it entirely.

this means that when using the mutable types, using `DateTime` is actually the right type to use for the property to actually benefit from phpstan reporting cases writing an invalid value.
This rule should be deprecated (and not enabled when enabling the doctrine code quality set).

**Comment by TomasVotruba** [comment]
> This rule should be deprecated (and not enabled when enabling the doctrine code quality set).

Sounds good, thanks for provided reasoning! :+1:

**Comment by TomasVotruba** [comment]
@samsonasik Could you look into this one? Let's deprecate it and remove it from the code quality set

**Comment by samsonasik** [comment]
@TomasVotruba sure, here the PR:

- https://github.com/rectorphp/rector-doctrine/pull/358
