### ISSUE TITLE
ImproveDoctrineCollectionDocTypeInEntityRector doesn't support indexedBy

### ISSUE THREAD

**Issue by yguedidi** [rectorphp/rector-doctrine#357]
It seems ImproveDoctrineCollectionDocTypeInEntityRector always add `int` index in the generic PHPdoc.
But when we use `indexedBy`, we can have `string indexes.

**Comment by samsonasik** [comment]
duplicated with https://github.com/rectorphp/rector/issues/8791

**Comment by samsonasik** [comment]
btw, it should be `indexBy` over `indexedBy`
