### ISSUE TITLE
[Attributes] Make sure nested Entity annotations are supported and split to own attributes

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector-doctrine#38]
![image](https://user-images.githubusercontent.com/924196/140508917-6de00860-0e85-41a3-bf4d-08e8fe10fac4.png)

In the end, 3 attributes should be created

See https://www.reddit.com/r/PHP/comments/q7ikzt/comment/hjc4y4l/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by TomasVotruba** [comment]
@samsonasik Could you check this one? Thanks

**Comment by samsonasik** [comment]
@TomasVotruba that's seems already fixed at rector dev-main by PR https://github.com/rectorphp/rector-src/pull/1099

**Comment by TomasVotruba** [comment]
I see, thanks for confirmation :+1:
