### ISSUE TITLE
[ORM 2.9] Add new set for migration of annotations to Attributes

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/rector-doctrine#4]
Package `doctrine/orm` 2.9 stable now supports PHP 8.0 attribute alternatives for Doctrine annotations.

See https://www.doctrine-project.org/2021/05/24/orm2.9.html

There is place for a first-time, who would like to chip-in little work to upgrade of every Doctrine  project in the world.

<br>

## 7 Steps to Contribute Doctrine ORM 2.9 Migration Set

1. look at existing sets https://github.com/rectorphp/rector-doctrine/tree/main/config/sets
2. add a new set, e.g. `doctrine-orm-29.php`
3. register `AnnotationToAttributeRector` rule - https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#annotationtoattributerector
4. configure it with all Doctrine annotations that have attribute alternatives 
5. first value is annotation class, second is attribute class - in this case they're always the same
5. e.g. for `ORM\Entity`, it would look like this

```php
 $services->set(AnnotationToAttributeRector::class)
        ->call('configure', [[
            AnnotationToAttributeRector::ANNOTATION_TO_ATTRIBUTE => ValueObjectInliner::inline([
                new AnnotationToAttribute(
                    'Doctrine\ORM\Mapping\Entity',
                    'Doctrine\ORM\Mapping\Entity'
                ),
            ]),
        ]]);
```

6. send PR
7. party and share it to help your Doctrine friends :tada: :birthday: :balloon: 

<br>

## Bonus Level

*Would be nice, but is not needed.*

Write a test so we have this behavior verified.

- [copy this test](https://github.com/rectorphp/rector-doctrine/tree/main/tests/Set/DoctrineRepositoryAsServiceSet)
- configure `rector.php` with `import('...-doctrine-orm-29.php')` set
- add single fixture file to `/Fixtures` directory to verify
- :+1:

**Comment by samsonasik** [comment]
I created a starting PR for it at https://github.com/rectorphp/rector-doctrine/pull/5 . If anyone want have more fixture examples of Doctrine annotation from there, feel free to cherry-pick commits and continue.
