### ISSUE TITLE
[Doctrine][Rules Overview][ImproveDoctrineCollectionDocTypeInEntityRector][Typo]

### ISSUE THREAD

**Issue by guelosuperstart** [rectorphp/rector-doctrine#6]
Hi @TomasVotruba , 

There seems to be a typo in this rule : `https://github.com/rectorphp/rector-doctrine/blob/main/docs/rector_rules_overview.md#improvedoctrinecollectiondoctypeinentityrector.`

`@var Collection<int, Training>|Trainer[]` -> `@var Collection<int, Trainer>|Trainer[]` ?

Thks

**Comment by TomasVotruba** [comment]
Hey, it's possible :) could you send PR to fix it?

**Comment by guelosuperstart** [comment]
Okay, I'll try to do it ;)

**Comment by TomasVotruba** [comment]
It should be modified in `ImproveDoctrineCollectionDocTypeInEntityRector.php`. The documentation markdown is only generated from it.
