### ISSUE TITLE
Rules not working for entities using php 8 attributes 

### ISSUE THREAD

**Issue by aszenz** [rectorphp/rector-doctrine#65]
We recently converted our doctrine entities to use php 8 attributes using rector and now we wish to apply some other rules but it seems like many rules don't work on attribute based entities.

I tried `TypedPropertyFromColumnTypeRector` rule, and it doesn't work on attribute based entities. It just shows `Rector is done!` message without changing anything even though there are many properties left un-typed.

To test I tried the same rule on old annotation based entity and it worked well.

Is there any way to use these rules now or will the attribute based entities require new rules?

**Comment by aszenz** [comment]
For this entity it works fine:

https://getrector.org/demo/1ec72f18-78a6-6630-a89d-334dbd12b287

The same entity using attributes it says no change:

https://getrector.org/demo/1ec72f18-25fa-6076-8e94-d77797fe6e88

**Comment by TomasVotruba** [comment]
I see. Could you add failing test fixture (the 2nd demo) in `TypedPropertyFromColumnTypeRectorTest` in `/Fixture` directory?
