### ISSUE TITLE
Doctrine decimal column type mapped incorrectly as float

### ISSUE THREAD

**Issue by aszenz** [rectorphp/rector-doctrine#68]
When applying the rule `TypedPropertyFromColumnTypeRector`

See https://getrector.org/demo/1ec73834-ba14-69bc-8cfe-29f5df412c73

Doctrine decimal type should be mapped to string to preserve precision as per:

https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#mapping-matrix
https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#decimal

In this case we can also use `numeric-string` var annotation to specify that it's a numeric string and not just any other string.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting and links.

The fix might require to change this type to `StringType`:  https://github.com/rectorphp/rector-doctrine/blob/4ce012666dd939e2956fbed329e5eef79179856f/src/NodeManipulator/ColumnPropertyTypeResolver.php#L56
