### ISSUE TITLE
Some rules produce no change for entities with native attributes

### ISSUE THREAD

**Issue by aszenz** [rectorphp/rector-doctrine#71]
Some other rules which don't work with entities annotated using php attributes instead of doc blocks

- [ ] TypedPropertyFromToOneRelationTypeRector
- [ ] TypedPropertyFromToManyRelationTypeRector 
- [ ] ImproveDoctrineCollectionDocTypeInEntityRector
- [ ] RemoveRedundantDefaultPropertyAnnotationValuesRector

Working on annotations: 
https://getrector.org/demo/1ec7452c-d213-6766-899c-53572d5e860c

No change on attributes:
https://getrector.org/demo/1ec7452b-e5a8-6bc4-b0d4-752ae0c535c0

**Comment by samsonasik** [comment]
@aszenz could you provide failing fixture with expected behavior for it? For multiple rules applied, you can add to https://github.com/rectorphp/rector-src/tree/main/tests/Issues
