### ISSUE TITLE
Rector forces FQN for `\Doctrine\DBAL\Types\Types`

### ISSUE THREAD

**Issue by simPod** [rectorphp/rector-doctrine#74]
```diff
use Doctrine\DBAL\Types\Types;

...

-    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
+    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::DATETIME_IMMUTABLE)]
```

`Types` is imported but rector still tries to force usage FQN when using `DoctrineSetList::DOCTRINE_CODE_QUALITY`.

**Comment by samsonasik** [comment]
You can enable auto import for it https://github.com/rectorphp/rector/blob/main/docs/auto_import_names.md
