### ISSUE TITLE
Initialize default collection property rule does not work on php attribute

### ISSUE THREAD

**Issue by aszenz** [rectorphp/rector-doctrine#78]
Rule: 
https://github.com/rectorphp/rector-doctrine/blob/main/docs/rector_rules_overview.md#initializedefaultentitycollectionrector

Reproducer: 

https://getrector.org/demo/1ec78515-bc82-6f9a-a506-77d427391643

**Comment by aszenz** [comment]
Failing fixture : [aszenz:patch-4](https://github.com/rectorphp/rector-doctrine/pull/79)

**Comment by TomasVotruba** [comment]
I've cherry picked the test in https://github.com/rectorphp/rector-doctrine/pull/80, thank you :+1:
